flat_genomics_functions.Rmd:
  path: dev/flat_genomics_functions.Rmd
  state: active
  R:
  - R/annotate_rsids.R
  - R/calc_credset.R
  - R/coloc_run.R
  - R/gg_manhattan_df.R
  - R/gg_qq_df.R
  - R/hyprcoloc_df.R
  - R/ldak_h2.R
  - R/magmar.R
  - R/metal_config.R
  - R/metal_run.R
  - R/mr_mega.R
  - R/plink_extract_ld.R
  - R/run_carma.R
  - R/s_multixcan.R
  - R/s_predixcan.R
  tests:
  - tests/testthat/test-gg_manhattan_df.R
  - tests/testthat/test-gg_qq_df.R
  - tests/testthat/test-annotate_rsids.R
  - tests/testthat/test-metal_config.R
  - tests/testthat/test-metal_run.R
  - tests/testthat/test-mr_mega.R
  - tests/testthat/test-plink_extract_ld.R
  - tests/testthat/test-hyprcoloc_df.R
  - tests/testthat/test-coloc_run.R
  - tests/testthat/test-calc_credset.R
  - tests/testthat/test-run_carma.R
  - tests/testthat/test-magmar.R
  - tests/testthat/test-s_predixcan.R
  - tests/testthat/test-s_multixcan.R
  - tests/testthat/test-ldak_h2.R
  vignettes: vignettes/genomics-functions.Rmd
  inflate:
    flat_file: dev/flat_genomics_functions.Rmd
    vignette_name: Genomics Functions
    open_vignette: true
    check: false
    document: true
    overwrite: ask
flat_miscellaneous.Rmd:
  path: dev/flat_miscellaneous.Rmd
  state: active
  R: R/render_datatable.R
  tests: tests/testthat/test-render_datatable.R
  vignettes: []
  inflate:
    flat_file: dev/flat_miscellaneous.Rmd
    vignette_name: .na
    open_vignette: false
    check: false
    document: true
    overwrite: 'yes'
keep:
  path: keep
  state: active
  R:
  - R/levinmisc-package.R
  - R/utils-pipe.R
  tests:
  - tests/testthat/test-description-of-your-package-submit-targets-sh.R
  - tests/testthat/test-populate_targets_proj.R
  vignettes: []
LPC_targets_project.Rmd:
  path: dev/LPC_targets_project.Rmd
  state: active
  R:
  - R/populate_targets_proj.R
  - R/use_crew_lsf.R
  tests: tests/testthat/test-use_crew_lsf.R
  vignettes: vignettes/create-a-new-targets-pipeline-for-lpc.Rmd
  inflate:
    flat_file: dev/LPC_targets_project.Rmd
    vignette_name: Create a New Targets Pipeline for LPC
    open_vignette: false
    check: false
    document: true
    overwrite: ask
