---
title: "flat_miscellaneous.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# Render DataTable to HTML

This function is a wrapper around the `DT::datatable` function, which renders a dataframe to an interactive html widget, containing useful defaults.

    
```{r function-render_datatable}
#' Render DataTable to HTML
#'
#' This function is a wrapper around the `DT::datatable` function, containing useful defaults. This function is particularly useful when to provide interactivity (eg. sorting, saving) to tables when rendering documents using RMarkdown or Quarto.
#'
#' @param df Dataframe to render
#' @param extensions Extensions parameter passed to `DT::datatable`
#' @param class Class parameters passed to `DT::datatable`
#' @param rownames (logical) Include rownames in output (Default = `FALSE`)
#' @param options List of options passed to `DT::datatable`
#' @param height Height of output (Default = `400`)
#' @param ... Additional arguments passed to `DT::datatable`
#'
#' @return An HTML widget
#'
#' @export
#'
#' @concept miscellaneous

render_datatable <- function(df,
                             extensions = c("Buttons"),
                             class = c("compact", "stripe", "hover", "row-border"),
                             rownames = FALSE,
                             options = list(
                               dom = "Bfrtip",
                               buttons = c("copy", "csv"),
                               scrollX = TRUE,
                               scrollY = TRUE
                             ),
                             height = 400,
                             ...) {
  DT::datatable(
    df,
    extensions = extensions,
    class = class,
    rownames = rownames,
    options = options,
    height = height,
    ...
  )
}
```
  
```{r example-render_datatable}
render_datatable(datasets::mtcars)
```
  
```{r tests-render_datatable}
test_that("render_datatable works", {
  expect_true(inherits(render_datatable, "function"))
})
```
  
```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly

fusen::inflate(flat_file = "dev/flat_miscellaneous.Rmd", vignette_name = "Miscellaneous Functions")
```
