# WARNING - Generated by {fusen} from dev/flat_genomics_functions.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("run_carma works", {
  expect_true(inherits(run_carma, "function"))
})
