# WARNING - Generated by {fusen} from dev/LPC_targets_project.Rmd: do not edit by hand

# Functions to allow creating files in new temporary directory
dir_empty <- function(x) {
  unlink(x, recursive = TRUE, force = TRUE)
  dir.create(x)
}

test_with_dir <- function(desc, ...) {
  new <- tempfile()
  dir_empty(new)
  withr::with_dir( # or local_dir()
    new = new,
    code = {
      tmp <- capture.output(
        testthat::test_that(desc = desc, ...)
      )
    }
  )
  invisible()
}

test_with_dir("populate_targets_proj creates log folder", {
  populate_targets_proj()
  expect_true(dir.exists("build_logs"))
})

test_with_dir("populate_targets_proj creates .clustermq_lsf.tmpl", {
  populate_targets_proj()
  expect_true(file.exists(".clustermq_lsf.tmpl"))
})

test_with_dir("populate_targets_proj creates .make-targets.sh", {
  populate_targets_proj()
  expect_true(file.exists(".make-targets.sh"))
})

test_with_dir("populate_targets_proj creates submit-targets.sh", {
  populate_targets_proj()
  expect_true(file.exists("submit-targets.sh"))
})

test_with_dir("populate_targets_proj creates pipeline and results .qmd templates", {
  populate_targets_proj()
  expect_true(length(fs::dir_ls(".", glob = "*-Results.qmd")) > 0)
  expect_true(length(fs::dir_ls(".", glob = "*-Pipeline.qmd")) > 0)
})

test_that("use_crew_lsf works", {
  expect_true(inherits(use_crew_lsf, "function"))
})
