# WARNING - Generated by {fusen} from dev/LPC_targets_project.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("use_crew_lsf works", {
  expect_true(inherits(use_crew_lsf, "function"))
})

test_that("use_crew_lsf defaults to the container runtime", {
  template <- suppressMessages(use_crew_lsf())
  expect_identical(
    as.character(template),
    as.character(suppressMessages(use_crew_lsf(runtime = "container")))
  )
  expect_true(grepl("singularity exec", template, fixed = TRUE))
  expect_true(grepl("export SINGULARITY_BIND=", template, fixed = TRUE))
  expect_false(grepl("module load", template, fixed = TRUE))
})

test_that("use_crew_lsf loads an R module under the native runtime", {
  template <- suppressMessages(use_crew_lsf(runtime = "native"))
  expect_true(grepl("module load R/", template, fixed = TRUE))
  expect_false(grepl("singularity exec", template, fixed = TRUE))
  expect_false(grepl("R_LIBS_USER", template, fixed = TRUE))
})

test_that("use_crew_lsf returns parseable R code for either runtime", {
  for (runtime in c("container", "native")) {
    template <- suppressMessages(use_crew_lsf(runtime = runtime))
    expect_true(length(parse(text = template)) > 0)
  }
})

test_that("use_crew_lsf rejects an unknown runtime", {
  expect_error(use_crew_lsf(runtime = "singularity"), "must be one of")
})
