# WARNING - Generated by {fusen} from dev/flat_genomics_functions.Rmd: do not edit by hand

test_that("coloc_run works", {
  expect_true(inherits(coloc_run, "function")) 
})

test_that("coloc_run returns a list", {
  
  locus_df1 <- tibble::tibble(trait = "A", rsid = letters, beta = runif(26, min = -1), se = runif(26, max = 0.2), p_value = runif(1, min = 1/1e5, max = 0.99), samplesize = 10000, maf = runif(26), type = "quant", case_prop = NA)
  locus_df2 <- tibble::tibble(trait = "B", rsid = letters, beta = runif(26, min = -1), se = runif(26, max = 0.2), p_value = runif(1, min = 1/1e5, max = 0.99), samplesize = 10000, maf = runif(26), type = "cc", case_prop = 0.2)
  
  locus_df <- dplyr::bind_rows(locus_df1, locus_df2)
  
  coloc_res <- coloc_run(locus_df)
  
  expect_true(inherits(coloc_res, "list")) 
})
