# WARNING - Generated by {fusen} from dev/flat_genomics_functions.Rmd: do not edit by hand

test_that("annotate_rsids works", {
  expect_true(inherits(annotate_rsids, "function"))
})

test_that("annotate_rsids returns a tibble", {
  df <- tibble(Chromosome = 1) %>%
    tidyr::crossing(Position = 1e4:1e5)
  rsids_res <- annotate_rsids(df)
  expect_s3_class(rsids_res, "data.frame")
})
