# WARNING - Generated by {fusen} from dev/LPC_targets_project.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("use_crew_lsf works", {
  expect_true(inherits(use_crew_lsf, "function"))
})
