# WARNING - Generated by {fusen} from dev/flat_genomics_functions.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("s_multixcan works", {
  expect_true(inherits(s_multixcan, "function"))
})
