# WARNING - Generated by {fusen} from dev/flat_miscellaneous.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("render_datatable works", {
  expect_true(inherits(render_datatable, "function"))
})
