# WARNING - Generated by {fusen} from dev/flat_genomics_functions.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("plink_extract_ld works", {
  expect_true(inherits(plink_extract_ld, "function"))
})
