# WARNING - Generated by {fusen} from dev/flat_genomics_functions.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("metal_config works", {
  expect_true(inherits(metal_config, "function"))
})
