# WARNING - Generated by {fusen} from /dev/LPC_targets_project.Rmd: do not edit by hand


#' Populate Targets Project
#'
#' @param title (character) base name for project files (eg. "{title}-Pipeline.qmd" and "{title}-Results.qmd")
#' @param log_folder (character) directory for LSF logs.
#'
#' @export

#' @examples
#' \dontrun{
#' populate_targets_proj("test")
#' }
populate_targets_proj <- function(title,
                                  log_folder = "build_logs",
                                  overwrite = FALSE){
  # Create title
  if(missing(title)) {
    title <- basename(here::here())
  }
  
  # Check if files already exist
  if(file.exists(".clustermq_lsf.tmpl") | file.exists("*-Results.qmd") | file.exists("*-Pipeline.qmd")) {
    cli::cli_alert_danger("Files already exist")
    overwrite <- yesno::yesno("Overwrite existing files?")
    if(!overwrite) cli::cli_abort("Exiting")
  }
  
  # Create build_logs folder
  fs::dir_create(log_folder)
  cli::cli_alert_success("Build log folder created at {.file {log_folder}}")
  
  # Copy clustermq lsf template
  fs::file_copy(fs::path_package("extdata", ".clustermq_lsf.tmpl", package = "levinmisc"), 
                ".clustermq_lsf.tmpl", 
                overwrite = overwrite)
  cli::cli_alert_success("Clustermq template created at {.file .clustermq_lsf.tmpl}")
  
  # Copy clustermq lsf template
  fs::file_copy(fs::path_package("extdata", "make-targets-10cores.sh", package = "levinmisc"), 
                "make-targets-10cores.sh", 
                overwrite = overwrite)
  cli::cli_alert_success("Clustermq template created at {.file make-targets-10cores.sh}")
  
  # Copy targets pipeline template
  fs::file_copy(fs::path_package("extdata", "Pipeline.qmd", package = "levinmisc"), 
                paste0(title, "-Pipeline.qmd"),
                overwrite = overwrite)
  cli::cli_alert_success("Targets Pipeline template created at {.file {paste0(title, '-Pipeline.qmd')}}")
  
  # Copy targets results template
  fs::file_copy(fs::path_package("extdata", "Results.qmd", package = "levinmisc"), 
                paste0(title, "-Results.qmd"),
                overwrite = overwrite)
  cli::cli_alert_success("Targets Results template created at {.file {paste0(title, '-Results.qmd')}}")
  
}
