# WARNING - Generated by {fusen} from dev/LPC_targets_project.Rmd: do not edit by hand

#' Create a minimal targets template in the current project
#' 
#' @description
#' This function creates a minimal targets template in the current directory. This includes creating a `Pipelines.qmd` file containing boilerplate for running analyses, and a `Results.qmd` file which can be used to visualize the results. Parallelization of the pipeline is implemented using [targets::tar_make()] and `crew.cluster`, using pre-filled using parameters specific to the LPC system at Penn.
#'
#' @param title (character) base name for project files (eg. "{title}-Pipeline.qmd" and "{title}-Results.qmd")
#' @param log_folder (character) directory for LSF logs
#' @param overwrite (logical) overwrite existing template files
#'
#' @export
#' @concept targets
#' @examples
#' \dontrun{
#' populate_targets_proj("test")
#' }

populate_targets_proj <- function(title,
                                  log_folder = "build_logs",
                                  overwrite = FALSE) {
  # Create title
  if (missing(title)) {
    title <- basename(here::here())
  }

  # Check if files already exist
  if (file.exists("*-Results.qmd") | file.exists("*-Pipeline.qmd")) {
    cli::cli_alert_danger("Files already exist")
    overwrite <- yesno::yesno("Overwrite existing files?")
    if (!overwrite) cli::cli_abort("Exiting")
  }

  # Create build_logs folder
  fs::dir_create(log_folder)
  cli::cli_alert_success("Build log folder created at {.file {log_folder}}")

  # Copy batch script for job submission
  usethis::use_template(".make-targets.sh",
                        save_as = ".make-targets.sh",
                        package = "levinmisc")
  cli::cli_alert_success("Submission template created at {.file .make-targets.sh}")

  # Copy batch script to submit targets job
  usethis::use_template("submit-targets.sh",
                        save_as = "submit-targets.sh",
                        package = "levinmisc")
  cli::cli_alert_success("Targets submission script created at {.file submit-targets.sh}")

  # Copy targets pipeline template
  usethis::use_template("Pipeline.qmd",
                        save_as = paste0(title, "-Pipeline.qmd"),
                        data = list(global_options = levinmisc::use_crew_lsf()),
                        package = "levinmisc")
  cli::cli_alert_success("Targets Pipeline template created at {.file {paste0(title, '-Pipeline.qmd')}}")

  # Copy targets results template
  usethis::use_template("Results.qmd",
                        save_as = paste0(title, "-Results.qmd"),
                        package = "levinmisc")
  cli::cli_alert_success("Targets Results template created at {.file {paste0(title, '-Results.qmd')}}")
}
