# WARNING - Generated by {fusen} from /dev/flat_miscellaneous.Rmd: do not edit by hand

#' Render DataTable to HTML
#' 
#' This function is a wrapper around the `DT::datatable` function, containing useful defaults.
#' 
#' @param df Dataframe to render
#' 
#' @return An HTML widget
#' 
#' @export
#' @examples
#' render_datatable(datasets::mtcars)
render_datatable <- function(df){
    DT::datatable(
      df,
    extensions = c("Buttons"),
    class = c("compact", "stripe", "hover", "row-border"),
    rownames = FALSE,
    # fillContainer = TRUE,
    options = list(
      dom = "Bfrtip",
      buttons = c("copy", "csv"),
      scrollX = TRUE,
      scrollY = TRUE
    ),
    height = 400
  )
}
