# WARNING - Generated by {fusen} from /dev/LPC_targets_project.Rmd: do not edit by hand

#' Use Crew LSF
#' 
#' @return string
#' 
#' @export
#' 
#' @examples
#' \dontrun{
#' use_crew_lsf()
#' }
use_crew_lsf <- function(){
  title <- basename(here::here())
  
  command <- glue::glue(
    "library(targets)
library(tarchetypes)
library(crew)
library(crew.cluster)

controller_local <- crew_controller_local(
  name = '{title}_local',
  workers = 1,
  seconds_idle = 10
)

controller_lsf_normal <- crew.cluster::crew_controller_lsf(
  name = '{title}_normal',
  workers = 20L,
  lsf_memory_gigabytes_limit = 16,
  script_dir = {tools::R_user_dir('crew.cluster', which = 'cache')},
  lsf_log_output = 'build_logs/test-%J.log',
  lsf_log_error = 'build_logs/test-%J.err',
  script_lines = c(
    \"#BSUB-q voltron_normal\",
    \"export R_LIBS_USER=$HOME/R/rocker-rstudio/4.0\",
    \"export SINGULARITY_BIND='/project/:/project/, /scratch/:/scratch/, /appl/:/appl/, /lsf/:/lsf/, /scratch/:/scratch, /static:/static'\",
    \"module load singularity\",
    glue::glue(\"singularity exec --pwd {getwd()} /project/voltron/rstudio/bioconductor-tidyverse_singularity-latest.sif \\ \")
  ),
  verbose = TRUE
)

controller_lsf_long <- crew.cluster::crew_controller_lsf(
  name = '{title}_long',
  workers = 150L,
  lsf_memory_gigabytes_limit = 10,
  script_dir = {tools::R_user_dir('crew.cluster', which = 'cache')},
  lsf_log_output = 'build_logs/test-%J.log',
  lsf_log_error = 'build_logs/test-%J.err',
  script_lines = c(
    \"#BSUB-q voltron_long\",
    \"export R_LIBS_USER=$HOME/R/rocker-rstudio/4.0\",
    \"export SINGULARITY_BIND='/project/:/project/, /scratch/:/scratch/, /appl/:/appl/, /lsf/:/lsf/, /scratch/:/scratch, /static:/static'\",
    \"module load singularity\",
    glue::glue(\"singularity exec --pwd {getwd()} /project/voltron/rstudio/bioconductor-tidyverse_singularity-latest.sif \\ \")
  ),
  verbose = TRUE
)

controller_lsf_highmem <- crew.cluster::crew_controller_lsf(
  name = '{title}_highmem',
  workers = 5L,
  lsf_memory_gigabytes_limit = 96,
  script_dir = {tools::R_user_dir('crew.cluster', which = 'cache')},
  lsf_log_output = 'build_logs/test-%J.log',
  lsf_log_error = 'build_logs/test-%J.err',
  script_lines = c(
    \"#BSUB-q voltron_normal\",
    \"export R_LIBS_USER=$HOME/R/rocker-rstudio/4.0\",
    \"export SINGULARITY_BIND='/project/:/project/, /scratch/:/scratch/, /appl/:/appl/, /lsf/:/lsf/, /scratch/:/scratch, /static:/static'\",
    \"module load singularity\",
    glue::glue(\"singularity exec --pwd {getwd()} /project/voltron/rstudio/bioconductor-tidyverse_singularity-latest.sif \\ \")
  ),
  verbose = TRUE
)

# define some global options/functions common to all targets
options(tidyverse.quiet = TRUE)

tar_option_set(
  packages = c('tidyverse', 'targets', 'tarchetypes', 'arrow', 'vroom', 'data.table', 'qs', 'gt', 'crew', 'crew.cluster'),
  controller = crew::crew_controller_group(controller_lsf_long, controller_lsf_normal, controller_lsf_highmem, controller_local),
  resources = tar_resources(
    crew = tar_resources_crew(controller = '{title}_normal')
  ),
  storage = 'worker',
  retrieval = 'worker',
  cue = tar_cue(format = FALSE)
)"
  )
  
  cli::cli_h1("Copy the below code to the `global` chunk in your targets project:")
  
  return(command)
}
